### PR TITLE
Split the GUI module into multiple parts to make it easier to handle

### PR DESCRIPTION
**Pull request by Duckwhale**
Let's... get... dangerous! :eyes:  

Roadmap:

- [x] Split the existing code into different files (one per area of responsibility)
- [x] Move library code (LibSink, LibQTip, ...) to separate wrappers in order to streamline the API

### CODE REVIEW

**Comment by Duckwhale** [comment]
Since this PR has been a WIP for ages, maybe it's time to split it up to get the changes merged (especially helpful to tackle #350 properly). 

Although I would consider it "unfinished", here's my thoughts on the changes thus far:

* Splitting the GUI into multiple parts based on the individual widgets seems like a good starting point for further refactoring
* The ``Core/GUI.lua`` is still a dumpster fire, but there's too much unrelated functionality that I can't easily move elsewhere
* In order to refactor the non-GUI code that's strewn all over the place, I'd want proper tests (i.e., #252) to avoid breaking everything
* This would require much more work and should likely be a separate GUI-related issue (or several)
* I also like the extraction of string and table utilities, despite it not being part of the GUI per se
* The 3rd party interfaces I don't like, at all
* I tried to gave them domain-specific names, instead of just doing ``TradeSkillMaster.lua`` and ``Rarity.TradeSkillMaster`` or similar
* This doesn't seem like the best design yet as it feels kind of awkward, but I don't want to block this PR just because of it

Any ideas, feedback etc. on the state/progress so far @godejord? Anything important missing that absolutely needs to be in?

We could merge this in despite its "unfinished" state and revisit the remaining problems after we have automated tests (i.e., hopefully soon).

**Comment by godejord** [comment]
This PR is massive, so it's hard to really give any detailed feedback. It does look a lot more manageble and clear at first glance. Unless you have taken some functionality out or broken anything in the process, then I'd say merge it as is, and take it from there. It's likely easier to see which parts are more pressing to refactor in the next iteration once we get a bit used to this new layout.

Also, like you said, this kinda have to get merged before any other issues regarding the GUI gets tackled. No way I want to experience merge conflicts with all this 😆

**Comment by Duckwhale** [comment]
Oh, yeah. It's a lot of changes, but if you read the commit history you'll see I didn't change any GUI code really. I split them into different files, did some minor refactoring, and tried to refactor more but realized it's too convoluted and risky without proper tests.

To proceed with anything else, I'd either have to "finish" this or we just split it off and I do it later, separately. Seems like a less risky approach :joy:

**Comment by Duckwhale** [comment]
Also, I guess if I did break something then I'l have to fix it. But I didn't notice any issues with the UI while testing, and haven't touched anything else.

**Comment by Duckwhale** [comment]
Just to make extra sure I'll push this alongside the recently-added 9.1 toys in an alpha release. Nothing like using players as QA, I guess :laughing:

**Pull request merged**
