### PR TITLE
Use built-in table.sort function for Sorting

### PR DESCRIPTION
**Pull request by AySz88**
One cause of #100 is that the sort_X functions in Sorting.lua currently use [selection sort](https://en.wikipedia.org/wiki/Selection_sort), which is notoriously slow, as it performs O(n^2) comparisons.

Lua offers `table.sort()`, a built-in for sorting arrays that can take custom comparators. This [SO thread](https://stackoverflow.com/questions/18043803/what-algorithm-does-table-sort-use) says that it is a C implementation of quicksort, but is not a stable sort (i.e. it may arbitrarily reorder ties). If this is a problem, the comparator can be extended to break ties explicitly. (There are also different O(n log n) algorithms that are stable, like [mergesort](https://en.wikipedia.org/wiki/Merge_sort), but that might not be necessary short of a UI for arbitrary user-specified sorts.)

Profiling on my machine, my worst sort (by zone, with no hidden items) is 680 ms, judging by the debug "AddGroup...Sort" outputs. There may be additional improvements available by making the comparators themselves faster, especially `compareZone`.

You might want to take this opportunity to rename `Sorting.sort2`, but to keep the diff focused, I haven't.

### CODE REVIEW

**Comment by Duckwhale** [comment]
Great stuff, thank you for the contribution!

I was thinking of using the builtin ``table.sort`` myself, assuming they'd use a C implementation of quicksort. I didn't have time to research if they also support comparators after profiling yesterday, as I was mostly focused on the LibQTip issue, but I'm glad to see it's all fairly standard :)

I don't think it's a problem that ties aren't resolved deterministically. I suppose we could make adjustments if it proves to be an issue, but I'll cross that bridge when I get there.

I'll have to clean up the leftovers from yesterday before merging this and I want to do some more profiling locally, but improving the worst case time to what's essentially the best case currently will be huge for anyone using these sort methods!

**Comment by Duckwhale** [comment]
Merging in all the smaller changes from yesterday created some merge conflicts. I'll resolve them locally in a bit.

**Comment by Duckwhale** [comment]
For the record, always branch from ``master`` as the individual branches are subject to change until they're ready to be merged. Since you used the branch I worked on yesterday and I didn't notice, merging in your change will be a bit of a headache I'm afraid :joy:

**Comment by AySz88** [comment]
Glad it helped! Sorry for rehashing what you'd known.

About the comparators, I did notice that `table.sort` specifies boolean while the current comparators return int or boolean arbitrarily. It doesn't seem to cause any error outright, though it might cause some conversion overhead, or block some optimization by the interpreter.

**Comment by Duckwhale** [comment]
I think I have to force-push to your branch; I hope it doesn't destroy anything of value. If there's an issue please let me know and don't pull in the updated branch so we can restore the original commits, though I hope it won't be necessary.

**Comment by Duckwhale** [comment]
> 
> 
> Glad it helped! Sorry for rehashing what you'd known.
> 
> About the comparators, I did notice that `table.sort` specifies boolean while the current comparators return int or boolean arbitrarily. It doesn't seem to cause any error outright, though it might cause some conversion overhead, or block some optimization by the interpreter.

Will have to look into the comparators, but we can easily update them to return ``false`` or ``nil`` instead of ``0`` if needed. We'd probably need to do some benchmarking first to see if it changes anything, but I'd assume it doesn't really change much since they all evaluate to ``false``.

**Comment by AySz88** [comment]
> I think I have to force-push to your branch; I hope it doesn't destroy anything of value. If there's an issue please let me know and don't pull in the updated branch so we can restore the original commits, though I hope it won't be necessary.

There isn't anything there other than this commit, no. I was expecting the PR to merge into your branch rather than into master? Is that not a function that github supports? Sorry about the complications. ^^;

**Comment by Duckwhale** [comment]
The problem is that the branch you wanted to merge in was just me experimenting and benchmarking; I've since split it into several smaller features that have been merged (except for the base branch). This means you now have the WIP commits and not what you had yesterday, but I'm trying to untangle the mess somehow :P

**Comment by Duckwhale** [comment]
Merged via #411, thanks again!

**Pull request closed without merging**
