### PR TITLE
fixes error caused by 10.1.5 updates

### PR DESCRIPTION
**Pull request by elkewtf**
This needs testing by someone else (works for me) but this should fix the error caused by the latest update from 10.1.5 that removed the artifact history ready function

### CODE REVIEW

**Comment by GurliGebis** [comment]
Are all of these changes needed?
It looks like it removed more than just the event handler and registration

**Comment by elkewtf** [comment]
> Are all of these changes needed? It looks like it removed more than just the event handler and registration

No it should have only been 3 total lines removed. 1 in each of the files that I edited. I wonder if my version was slightly different. HOld please. I'll reclone and make a new PR.

**Comment by GurliGebis** [comment]
You could just amend the commit and force push the branch 🙂
But that works as well 👍

**Comment by elkewtf** [comment]
Yeah except I have no idea how those others changes were pulled in. Haha I didn't trust it.

**Pull request closed without merging**
