### PR TITLE
Expose lastAttempts in options screen for obtained items

### PR DESCRIPTION
**Pull request by conundrum89**
Intended as a stopgap solution to #172. The actual issue seems to just be that the Attempts counter resets when an item is obtained, and the attempt count is stored in lastAttempts instead:

`get = function(into)
    return tostring((item.attempts or 0) - (item.lastAttempts or 0))
end`

So I am simply displaying lastAttempts in a description field above the Attempts / Chance boxes, if lastAttempts > 0, and otherwise displaying "Not Obtained" (it might not always be accurate to say an item has not been obtained if lastAttempts is 0, but I can't seem to find any more useful way to determine whether that's the case).

### CODE REVIEW

**Comment by Duckwhale** [comment]
Thanks for your contribution! Apologies for the late reply, I forgot after initially seeing the PR :)

I can imagine there'd be some issues with inaccuracies and possibly the user experience/UI. I'll need to check this out locally and test for a bit before I can say more, which hopefully I'll find time to do very soon (TM)!

**Comment by conundrum89** [comment]
No worries at all, I'm pretty new to WoW addons (have only really done small local modifications until now) so definitely open to feedback or pointers on where things are XD

**Comment by Duckwhale** [comment]
Alright, so I take a look and I think this is a great idea! Unfortunately, there's some problems I can see:

1. If a mount has been learned, it still shows "Not obtained" for me
2. The text and formatting might benefit from some visual improvements (but that's hardly an issue)
3. It obviously only shows the last attempts count, not all of them (which would essentially resolve #12)

So what can we do about these? Let's see...

1. This is tricky and might warrant a separate issue (to be resolved later), especially since ``lastAttempts`` is used in multiple parts of the addon currently... including the GUI that's already being refactored (#329 )
2. I think just rephrasing the text to make it clear it's not a "guaranteed display" but rather "this might hopefully be right" could be enough. Not sure how to improve the formatting at the moment as that appears to be related to AceConfig
3. Again a separate issue, we could add an entirely new "statistics" header and also include this part there. The difficulty here is mostly that we can't query historical data properly yet and would therefore have to rely on similar hacks to this one. And of course the configuration UI is likely the wrong place for displaying statistics anyway, although I wouldn't consider that big deal for a temporary measure such as this

**Comment by conundrum89** [comment]
Thanks for taking a look!

1. As far as I can tell, it will display "Not Obtained" for an obtained mount only if Rarity doesn't know about the attempts that got you the mount. For example, this happens for me on the Jaina mount because I got it during 8.3, when Rarity didn't track it, so I have lastAttempts = 0 for that mount - but I guess it could also happen if Rarity lost data, or you didn't have an import string for the mount when you got it, or probably any myriad of other reasons! Maybe instead of "Not Obtained" I could make it say "No Previous Attempts Recorded"?
2. I'm not very familiar with the AceConfig stuff, but perhaps there's a more appropriate content type than "description". Is there some other text used elsewhere in Rarity that looks how you'd like this to look? I can figure out how to replicate that here.
3. We can display the total number of attempts (we think) a user has ever had on an item pretty easily - that's just stored in Attempts. It would be cool to track the number of attempts each time an item was obtained and display them in a list or something, and maybe even then display "average attempts per drop" etc, but that information doesn't seem to exist historically - lastAttempts is overwritten each time the item is obtained, and doesn't seem to be recorded anywhere else, unless there's a hidden database of attempt counts that I missed in my (admittedly cursory) searching.

Perhaps for now I put this information up the top (where Drop: and Location: etc are printed), so that it's not displayed alongside configuration fields, and expand it to say "Total Attempts: " and "Last Obtained In: " _or_ "No Previous Attempts Recorded" depending on the data we have. Thoughts?

**Comment by Duckwhale** [comment]
1. Yup, I was thinking something along the lines would be better, as it's very likely not all attempts are still available. Even when relying on Blizzard's statistics, we can only see the total number of kills and not when the mount was actually obtained :(
2. No idea, honestly, if you want to improve this you'll have to check their documentation [here](https://www.wowace.com/projects/ace3/pages/ace-config-3-0-options-tables). Unfortunately I've almost never touched that part so I can't really help, but if you don't want to deal with it that's also fine and we can just improve it later - your choice! :)
3. As far as I know, we don't gather many more statistics than the time/date of an attempt. We could probably derive more information from that but it won't be available for every item, and definitely require a better UI to display. That's part of the issue I linked, so it doesn't have to be in this PR at all

Sounds like a good idea! Feel free to improve this until you're happy with it, or just let me know and we can merge as it is.

**Comment by conundrum89** [comment]
Updated! It now displays only relevant fields (Current Attempts, plus Total and Last Attempts only if they're different from Current Attempts) at the top of the listing (after source information). It'll never say "Not Obtained" since we just won't show "last attempts" in that case. Happy to merge it like this if you don't see any issues :)

**Comment by Duckwhale** [comment]
Thank you! I'm sure the UX could be improved further, but that can wait until the Options UI has been cleaned up a bit (soon™).

I'll merge this as-is and we can start rolling it out to people with the next alpha :)

**Pull request merged**
